### PR TITLE
Mongodb add task

### PR DESCRIPTION
**Pull request by Nalipp**
Added repository.js addTask() and wrote test

### CODE REVIEW

**Comment by Nalipp** [comment]
Hmm not sure why checks are failing, both mocha and standard are passing before push

**Comment by mepda** [comment]
if you check the travisCI page, you'll see that there's a problem with the "before hook"

**Comment by mepda** [comment]
looks like there's something testing that the object is null, but we already created a few objects instead

**Comment by Nalipp** [comment]
I did see the logs but really not sure what "before all hook" is referring to. The tests are green on my machine but fail when they are pushed to github. There are no tests were we assert null. And there is no "MongoClient.connect" code in test/repositoryTest.js so really not sure.

**Comment by DaleSeo** [comment]
The `mongodb_fixTests` branch contains these changes so no need to merge this.

**Pull request closed without merging**
