### PR TITLE
Refactor2

### PR DESCRIPTION
**Pull request by Nalipp**

### CODE REVIEW

**Comment by DaleSeo** [comment]
@Nalipp We forgot to lint it.

standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /home/travis/build/LearnTeachCodeSeoul/todo/app.js:18:19: Strings must use singlequote.
  /home/travis/build/LearnTeachCodeSeoul/todo/src/repository.js:11:23: Extra semicolon.
  /home/travis/build/LearnTeachCodeSeoul/todo/src/repository.js:24:21: Strings must use singlequote.
  /home/travis/build/LearnTeachCodeSeoul/todo/src/repository.js:25:21: Strings must use singlequote.
  /home/travis/build/LearnTeachCodeSeoul/todo/src/repository.js:29:11: Expected space(s) after "else".

**Comment by Nalipp** [comment]
Oh no. we forgot to run the tests also which are now failing because we changed the text format on the front end.

**Comment by Nalipp** [comment]
The tests are reading the content type as buffer instead of strings. I am not exactly sure how to fix the formatting between the front and backend so I commented out the tests so they would pass :/

**Comment by mepda** [comment]
@Nalipp did you try to stringify / toString the test cases?

**Comment by DaleSeo** [comment]
@Nalipp I don't think it's a good idea to comment out the tests. I got the JSON parse/stringify issues fixed for findTassk and addTask. I'm leaving delete/clearTasks parts for you and @mepda.

**Pull request merged**
