### PR TITLE
Travis CI Integration

### PR DESCRIPTION
**Pull request by DaleSeo**
Don't worry that you guys don't understand what's going on here.
I'll walk you guys through about this next weekend.

### CODE REVIEW

**Comment by mepda** [comment]
Looking forward to learning more about this on Saturday!

**Comment by mepda** [comment]
Three options to merge-- not sure how to proceed. Create a merge commit, squash and merge, or rebase and merge?

**Comment by DaleSeo** [comment]
@mepda I have no idea what you're talking about so I've just merged this pull request myself.

**Comment by mepda** [comment]
Okok looks like "merge commit" was the way to go.

**Pull request merged**
